services: 
    server:
      image: 'nginx:stable-alpine'
      ports: 
        - '8000:8000'
      volumes: 
        - ./src:/var/www/html
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on: 
        - php
        - mysql
    php:
      build:
        context: .
        dockerfile: ./dockerfiles/php.dockerfile
      volumes: 
        - ./src:/var/www/html:delegated
    mysql:
      image: mysql:5.7
      env_file: 
        - ./env/mysql.env
    composer:
      build:
        context: .
        dockerfile: ./dockerfiles/composer.dockerfile
      volumes: 
        - ./src:/var/www/html
    # artisan:
    # npm: